"""Static, Tk-independent text for the supported runtime languages."""

from __future__ import annotations


SUPPORTED_LANGUAGES = ("en", "zh-CN")

_TEXT = {
    "en": {
        "idle": "Idle",
        "thinking": "Thinking",
        "tool_call": "Calling tool",
        "command": "Running command",
        "output": "Outputting",
        "status": "Status",
        "preview_output": "●  Codex Outputting",
        "preview_active_conversations": "Active conversations  1",
        "preview_five_hour_quota": "5-hour quota   -- / --",
        "preview_weekly_quota": "Weekly quota   88%",
        "preview_reset_credit": "Reset Credit   4 times",
        "completed": "Completed",
        "no_active_conversations": "No active conversations",
        "active_conversations": "Active conversations {count}",
        "recent_conversation_completed": "Recent conversation completed",
        "session_directory_unreadable": "Session directory unavailable",
        "activity": "Codex {detail}",
        "quota_unavailable": "Quota unavailable",
        "week": "Week",
        "reset_credit": "Reset {count} times",
        "stale": "(quota stale)",
        "tray_error": "Tray icon error",
        "settings_title": "Codex Status Pet Settings",
        "language": "Language",
        "english": "English",
        "simplified_chinese": "Simplified Chinese",
        "opacity": "Opacity",
        "window_size": "Window size",
        "default_position": "Default position (X, Y)",
        "refresh_interval": "Refresh interval (seconds)",
        "always_on_top": "Always on top",
        "lock_position": "Lock position",
        "battery_content": "Battery display content",
        "five_hour": "5-hour",
        "weekly": "Weekly",
        "show_five_hour": "Show 5-hour quota",
        "show_weekly": "Show weekly quota",
        "show_reset_credit": "Show reset credit",
        "font_color": "Font color...",
        "background_color": "Background color...",
        "save": "Save",
        "apply": "Apply",
        "restore_defaults": "Restore Defaults",
        "close": "Close",
        "invalid_settings_title": "Invalid settings",
        "invalid_settings_message": "Coordinates and refresh interval must be valid numbers.",
        "protected_settings_title": "Configuration protected",
        "protected_settings_message": "The original configuration is incompatible or damaged. Choose Restore Defaults before saving to replace it.",
        "settings": "Settings",
        "hide_window": "Hide window",
        "exit": "Exit",
        "show_window": "Show window",
        "open_settings": "Open settings",
        "compact": "Compact",
        "existing_instance": "Codex Windows Status Pet is already running.\nClose the existing instance before launching this copy.",
    },
    "zh-CN": {
        "existing_instance": "Codex 状态宠物已在运行。\n请先关闭当前实例，再启动此副本。",
        "idle": "空闲",
        "thinking": "思考中",
        "tool_call": "调用工具",
        "command": "执行命令",
        "output": "输出中",
        "status": "状态",
        "preview_output": "●  Codex 输出中",
        "preview_active_conversations": "活动对话 1 个",
        "preview_five_hour_quota": "5 小时额度   -- / --",
        "preview_weekly_quota": "每周额度   88%",
        "preview_reset_credit": "重置次数   4 次",
        "completed": "已完成",
        "no_active_conversations": "没有活动中的对话",
        "active_conversations": "活动对话 {count} 个",
        "recent_conversation_completed": "最近对话已完成",
        "session_directory_unreadable": "会话目录不可读",
        "activity": "Codex {detail}",
        "quota_unavailable": "额度暂不可用",
        "week": "周",
        "reset_credit": "重置 {count} 次",
        "stale": "（额度过期）",
        "tray_error": "托盘图标异常",
        "settings_title": "Codex 宠物设置",
        "language": "语言",
        "english": "English",
        "simplified_chinese": "简体中文",
        "opacity": "透明度",
        "window_size": "窗口大小",
        "default_position": "默认位置 (X, Y)",
        "refresh_interval": "刷新间隔 (秒)",
        "always_on_top": "置顶",
        "lock_position": "锁定位置",
        "battery_content": "电池显示内容",
        "five_hour": "5小时",
        "weekly": "每周",
        "show_five_hour": "显示 5 小时额度",
        "show_weekly": "显示周额度",
        "show_reset_credit": "显示重置次数",
        "font_color": "字体颜色...",
        "background_color": "背景颜色...",
        "save": "保存",
        "apply": "应用",
        "restore_defaults": "恢复默认值",
        "close": "关闭",
        "invalid_settings_title": "设置无效",
        "invalid_settings_message": "坐标和刷新间隔必须填写合法数字。",
        "protected_settings_title": "配置受保护",
        "protected_settings_message": "原配置不兼容或已损坏。若要替换它，请先选择“恢复默认值”，再保存。",
        "settings": "显示设置",
        "hide_window": "隐藏窗口",
        "exit": "退出",
        "show_window": "显示窗口",
        "open_settings": "打开设置",
        "compact": "收缩",
    },
}


def normalize_language(value):
    """Return a supported code and an optional normalization warning."""
    if value in SUPPORTED_LANGUAGES:
        return value, None
    if value is None:
        return "en", None
    return "en", "language is invalid; English retained"


def translate(language, key, **format_values):
    """Return one translated user-facing string or fail visibly for a bad key."""
    normalized, _warning = normalize_language(language)
    return _TEXT[normalized][key].format(**format_values)
